# 基本学期信息
message: LNTUHelper iOS App 公测开始啦，小伙伴们欢呼雀跃吧，Local-Server 正常
sentryUrl: https://"*********"@o396131.ingest.sentry.io/5249091
semesterStartDate: 2020-08-31 # 用于计算学期和教学周

# 线上、测试数据库
mysql:
  host: localhost
  port: 3306
  user: demo
  password: demo
  database: demo # 线上数据库名
  testDatabase: test_demo # 测试数据库名

# 教务、素拓有效测试账号
account:
  educationUsername: 123456789
  educationPassword: 123456789
  qualityUsername: 123456789
  qualityPassword: 123456789
